### ISSUE TITLE
Omni for Emacs

### ISSUE THREAD

**Issue by Mdsp9070** [getomni/omni#12]
## Add a new theme to the organization?

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template).
- [x] The theme follows the Omni Color Palette.
- [x] The branch name is `main` (we will keep this name pattern from now on)
- [x] The theme has instructions on how to install it.

**Application:** Emacs text editor
**GitHub URL:** https://github.com/Mdsp9070/emacs

So, this is my first attempt to port Omni theme to Emacs, it maybe have some minor improvents to do but the base is done.

I changed a bit the template to fit with Emacs unique configs and so on... Also, when this theme will have been accepted, I'll publish the package to `MELPA` repositories (https://github.com/melpa/melpa).

I tried to support all most used packages, but of course there are infinite other that would require some minor tweaks.

I'd like to ask you all if there are any suggestions to improve the Mode-line and the theme itself.

My toughts:

1. Maybe the true colors variants are too lightened?
2. Mode-line appears to be too much darkened?
3. Fringe column and background are too different?
4. I don't know why, but there is a light white bar that represents tabs void (but this occurs on all themes, on my emacs config)

Any suggestions or PR would be perfect!

Here's a quick screenshot with true colors support:
![screenshot](https://user-images.githubusercontent.com/44469426/108600466-1fb19900-7376-11eb-9f10-6ae58f1883d9.png)

**Comment by Mdsp9070** [comment]
### UPDATE

I did some changes:

- darkened a little true colors variants
- added support for centaur tabs
- corrected all font-locks colors
- set line number column as same color of fringe and background
- added pink and yellows color and yours lighter variants

This is the actual state:

![screenshot](https://user-images.githubusercontent.com/44469426/108889268-f3528280-75ea-11eb-8672-9bf0f61263c3.png)

About those white bar of tabs voids: was a misconfig of my centaur tabs package!
I only needed to eval this functionn:
```elisp
(centaur-tabs-headline-match)
```

**Comment by Javiercuba** [comment]
i liked it

**Comment by jpedroschmitz** [comment]
It looks great to me @Mdsp9070!

I'll request a small minor change. Is it possible to add the `Mode-line format` section on the install file?
This file content will be listed on the website when we create it.

**Comment by Mdsp9070** [comment]
Of course! Do tou think that the supported packages lists need to be on install file too?

**Comment by jpedroschmitz** [comment]
I think we can keep it on the readme and maybe add a note on the install file linking to this section on the readme.

**Comment by Mdsp9070** [comment]
Oh, great idea! I will add a note to link!

**Comment by Mdsp9070** [comment]
Ok, I changed! I'll create the PR

**Comment by jpedroschmitz** [comment]
Great job overall. The theme looks awesome. 💜 

Don't forget to share it on social media, forums, and communities!

_ps: Always wait for approval before transferring the repository to the org! I'll add the `awaiting-transfer` label when it's ready!_
