### ISSUE TITLE
Omni for Vivaldi Browser

### ISSUE THREAD

**Issue by ThiagoG8** [getomni/omni#14]
## Add a new theme to the organization?

If you have already created a theme, make sure you check the following requirements:

- [X] The theme follows the [template](https://github.com/getomni/template).
- [X] The theme follows the Omni Color Palette.
- [X] The branch name is `main` (we will keep this name pattern from now on)
- [X] The theme has instructions on how to install it.

**Application:** Vivaldi Browser
**GitHub URL:** https://github.com/ThiagoG8/Vivaldi

OBS: I changed the INSTALL.md model a little to make it easier to configure the browser and I didn't add some colors from the palette because the browser is only possible with 5 colors: background, foreground, selection and accent color.

hopefully it will be accepted even with these changes.

and if something does not meet the requirements answer me for the issue.

**Comment by diego3g** [comment]
@ThiagoG8 I kinda dislike the color on the address bar and the active tab, i made a vivaldi theme by myself and switched it to a darker version.

What do you think about? Do you mind changing it?

![image](https://user-images.githubusercontent.com/2254731/108752979-ea967980-7522-11eb-8def-d99e85407add.png)

**Comment by ThiagoG8** [comment]
@diego3g OK I'm going to make some changes and I don't mind changing a few things.

**Comment by ThiagoG8** [comment]
I made some changes to look like the image you uploaded

That was the result

![2021-02-22 17 21 25 github com 94ebb5aeffa7](https://user-images.githubusercontent.com/57069875/108772816-41f51380-753c-11eb-86c4-46d08f174ac1.png)

**Comment by jpedroschmitz** [comment]
Hey @ThiagoG8, thanks for updating the theme. It looks great!

Could you update the config file on your repo so that we can start the migration process?

**Comment by ThiagoG8** [comment]
I just updated the color palette and screenshot.

now the repository is in accordance with the image.

**Comment by jpedroschmitz** [comment]
Thanks, @ThiagoG8!

I think we are ready to include the theme in the organization!  🎉 

I'll be sending an invite for you to join the organization. After that, you can transfer your repository to the org.

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

**Comment by jpedroschmitz** [comment]
Hey, I see you have transferred the repository!

If possible, please open a PR to add it to the list on the main repository!

Also, don't forget to share the theme on social media, communities, and forums!

Thanks!
