### ISSUE TITLE
Omni for Windows Terminal

### ISSUE THREAD

**Issue by joaonery** [getomni/omni#2]
**What would you like to be added**:
Windows Terminal.

**Why is this needed**:
This is a new terminal of Windows maded by Microsoft, it have been gain a lot of popularity and my idea was to develop a theme for it.

**Is your enhancement request related to a problem? Please describe.** 
There is a URL to my repository that resolve this problem:
https://github.com/joaonery/windows-terminal

**Additional context**
We can see the result on the image attached.
![screenshot](https://user-images.githubusercontent.com/39193813/108222831-e8de4780-7117-11eb-8d40-1c5920eb7f08.png)

**Comment by IagooCesaar** [comment]
I have interest on this feature too

**Comment by ialexanderbrito** [comment]
Very good, I also ended up doing manuals on mine and I recommend it highly.

**Comment by jpedroschmitz** [comment]
Hey @joaonery, nice. Thanks for creating the theme!

I think the theme is ready to be included in the organization 🎉 

I'll be sending an invite for you to join the organization. After that, you can transfer your repository to the org.

Just make sure also to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by joaonery** [comment]
Hey @jpedroschmitz, when I try to transfer my repository to the org, I receive a notification with "You don’t have the permission to create public repositories on getomni"

**Comment by jpedroschmitz** [comment]
Can you try again? I have updated the settings.

**Comment by joaonery** [comment]
@jpedroschmitz All done :), I move the repository and the PR was created

**Comment by jpedroschmitz** [comment]
Thanks! We can close this issue!

The theme can be found at [https://github.com/getomni/windows-terminal](https://github.com/getomni/windows-terminal) 🎉

**Comment by IagooCesaar** [comment]
Thank you! The theme has been applied successfully on my Windows Terminal
