### ISSUE TITLE
Omni for Alfred 4

### ISSUE THREAD

**Issue by demartini** [getomni/omni#20]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [X] The theme follows the [template](https://github.com/getomni/template);
- [X] The theme follows the Omni Color Palette;
- [X] The branch name is `main` (we will keep this name pattern from now on);
- [X] The theme has correct instructions on how to install it;
- [X] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Alfred 4
**Application URL:** https://alfredapp.com
**GitHub URL:** https://github.com/demartini/alfred

**Comment by jpedroschmitz** [comment]
Hey @demartini, thanks for creating the theme. It's awesome!

I have reviewed it, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization.

Before transferring the repo, make sure to change all URLs to match the new repository link.

Also, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by demartini** [comment]
Hello @jpedroschmitz, I am not able to transfer the repository, I do not have sufficient permissions.

> You don’t have the permission to create public repositories on getomni

Btw, I have already made all the necessary changes and opened the PR: #21

**Comment by jpedroschmitz** [comment]
Could you please try again? I think I've added the correct permissions now =D

**Comment by demartini** [comment]
Done!

By the way, I'm almost finishing the themes for iTerm and Terminal.app.

**Comment by jpedroschmitz** [comment]
That's great! As soon as you finish, please submit it here, and let's add it to the organization!

Don't forget to share about the theme (if you post something on Twitter, [mention me](https://twitter.com/jpedroschmitz) =D)

Also, make sure to read the [maintaining a theme](https://github.com/getomni/omni/blob/main/CONTRIBUTING.md#maintaining-a-theme) section. 
It's a small guide with some tips on how to maintain an Omni theme!

**Comment by demartini** [comment]
Hey @jpedroschmitz, I just saw that the actions are disabled in the repository, we need it activated so that we can release the new versions when the source code is changed.

**Comment by jpedroschmitz** [comment]
Hey, I've activated the action for the repository! Thanks for pointing this out 👊🏻
