### ISSUE TITLE
Omni for Gnome Terminal

### ISSUE THREAD

**Issue by gustavojuneo** [getomni/omni#22]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Gnome Terminal
**Application URL:** https://wiki.gnome.org/Apps/Terminal
**GitHub URL:** https://github.com/gustavojuneo/gnome-terminal

**Comment by jpedroschmitz** [comment]
Hey @gustavojuneo, thanks for creating the theme, just some small considerations after transferring it to the org:

1. On the CODEOWNERS file, change the username from jpedroschmitz to gustavojuneo.

2. Change all repository links to match the Omni link (https://github/getomni/gnome-terminal).

That's it. Let me know when you adjust; then we can move it to the Omni org 🚀

**Comment by jpedroschmitz** [comment]
Hey @Mdsp9070, I have reviewed it again, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization. After that, you can transfer your repository to the org.

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by Mdsp9070** [comment]
@jpedroschmitz, did you wrongly mention I?

**Comment by jpedroschmitz** [comment]
Yeh, sorry! I copied the message from another issue and forgot to change the username 😂

**Comment by gustavojuneo** [comment]
@jpedroschmitz , I did the PR I am not sure if it is right, because it is the first first pull request.

**Comment by jpedroschmitz** [comment]
Hey, everything looks fine! You have transferred the repository, and now it is under the Omni organization. 🎉 

Now you need to create a PR to add it to this main repository! If you need any help, let me know.

Don't forget to share the theme on forums, communities, and social media!

Thanks for creating it 💜

**Comment by gustavojuneo** [comment]
I've already created the PR with commit 'add Gnome Terminal to list'

**Comment by Mdsp9070** [comment]
> Yeh, sorry! I copied the message from another issue and forgot to change the username

no problem hahahah
