### ISSUE TITLE
Omni for JetBrains IDEs

### ISSUE THREAD

**Issue by Mayconsgs** [getomni/omni#32]
## New theme idea

I've developed a theme for JetBrains IDEs and IDEs based on IntelliJ. The theme is still on a test version. But it can already be used through manual installation.

In the future, I'd like to publish it on the JetBrains plug-ins store. However, in order to do that, I have some questions about who would be responsible for publishing, me or the organization. That's why I haven't done it yet. But I've followed every publishing guideline demanded by JetBrains.

## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** JetBrains IDEs
**Application URL** https://www.jetbrains.com/idea
**GitHub URL:** https://github.com/Mayconsgs/jetbrains

**Comment by jpedroschmitz** [comment]
Hey @Mayconsgs, thanks for creating this theme! It looks awesome 🚀 

When contributing to this project, refrain from using any other language than English. 💜 

If possible, complete all requirements and update your issue to English. If you need any help, let me know. 👊🏻 

After that, let's add the theme to the organization so that everyone can try it out.

**Comment by Mayconsgs** [comment]
Okay @jpedroschmitz, changes made.

**Comment by jpedroschmitz** [comment]
Hey @Mayconsgs, I really appreciate the changes!

I have reviewed it, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization.

Before transferring the repo, make sure to change all URLs to match the new repository link.

Also, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by Mayconsgs** [comment]
Hey @jpedroschmitz, I did all the steps, but I think there was a bug in the workflow. 

There is one that has been running for longer than normal. Would you be able to stop?

**Comment by jpedroschmitz** [comment]
Hey, thanks again!

We really appreciate your help and effort in creating the theme!

I've tried to stop the workflow, but the workflow run is not being canceled for some weird reason. 

Also, don't forget to share about the theme (if you post something on Twitter, [mention me](https://twitter.com/jpedroschmitz) =D)

And last but not least, make sure to read the [maintaining a theme](https://github.com/getomni/omni/blob/main/CONTRIBUTING.md#maintaining-a-theme) section. 
It's a small guide with some tips on how to maintain an Omni theme!
