### ISSUE TITLE
Omni for Mattermost

### ISSUE THREAD

**Issue by gprando** [getomni/omni#36]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Mattermost
**Application URL:** https://mattermost.com
**GitHub URL:** https://github.com/gprando/mattermost

**Comment by jpedroschmitz** [comment]
Thanks for creating another great theme, @gprando! It looks awesome 🚀 

Since you are already a member of the organization, you can transfer your repository!

**Comment by gprando** [comment]
@jpedroschmitz transfer completed, added links and opened [#PR39](https://github.com/getomni/omni/pull/39)

**Comment by jpedroschmitz** [comment]
Thanks, @gprando!

Make sure to read the [maintaining a theme](https://github.com/getomni/omni/blob/main/CONTRIBUTING.md#maintaining-a-theme) section. 
It's a small guide with some tips on how to maintain an Omni theme!
