### ISSUE TITLE
Add Gnome Terminator support

### ISSUE THREAD

**Issue by cmosetick** [getomni/omni#37]
Thanks for Omni theme!

Gnome Terminator is long running project (started in 2007) to expand upon the core functionality within Gnome Terminal.
In summary, Terminator offers a lot of the same core functionality that iTerm2.app offers on MacOS. (broadcast input, split windows, etc.)

I have made some small attempts to port Omni to Terminator.
However, I have run into issues with things like DIR COLORS and certain CLI applications not working properly with the Omni theme. e.g. `cointop`

I propose that Gnome Terminator get first class support with the Omni color pallet Theme.

**Application:** GNOME Terminator
**Application URL** https://gnome-terminator.org/
**GitHub URL:** https://github.com/gnome-terminator/terminator

More info about current developers:
https://github.com/gnome-terminator/terminator/issues/1

Info from APT repositories:

```
aptitude show terminator

Package: terminator                      
Version: 1.91-4ubuntu1
State: installed
Automatically installed: no
Priority: optional
Section: universe/misc
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 2,149 k
Depends: python3-cairo, python3-configobj, python3-dbus, python3-gi,
         python3-gi-cairo, python3-psutil, gir1.2-glib-2.0, gir1.2-gtk-3.0,
         gir1.2-pango-1.0, gir1.2-vte-2.91, dbus-x11, python3:any
Recommends: gir1.2-keybinder-3.0, gir1.2-notify-0.7, xdg-utils
Provides: x-terminal-emulator
Description: multiple GNOME terminals in one window
 Terminator is a little project to produce an efficient way of filling a large
 area of screen space with terminals. 
 
 The user can have multiple terminals in one window and use key bindings to
 switch between them. See the manpage for details.
Homepage: https://gnometerminator.blogspot.com/p/introduction.html
```

**Comment by ermesonsampaio** [comment]
Hey @cmosetick, I created a repository to port the omni terminator.

**Repository URL:** https://github.com/ermesonsampaio/terminator
**Issue:** #55

I tested the `cointop` and got this result:

![cointop](https://user-images.githubusercontent.com/87838931/135176479-916eb64c-6689-4907-ad67-2acb0f2a4a88.png)

**Comment by jpedroschmitz** [comment]
The theme is available at https://github.com/getomni/terminator 🎉

**Comment by cmosetick** [comment]
This is really awesome, thanks for the time spent on this guys! @ermesonsampaio @jpedroschmitz
