### ISSUE TITLE
Omni for Prism.js

### ISSUE THREAD

**Issue by martins-rafael** [getomni/omni#41]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Prism.js
**Application URL** https://prismjs.com/
**GitHub URL:** https://github.com/martins-rafael/prismjs

**Comment by diego3g** [comment]
Hello @martins-rafael, thanks for the contribution.

I saw the screenshot inside the theme URL but it seems that the colors are not matching between the code i write inside VSCode and PrismJS, can you take a look on it?

![code](https://user-images.githubusercontent.com/2254731/119043996-08dc0c00-b990-11eb-845d-9fc3b10def48.png)

**Comment by martins-rafael** [comment]
Hey @ diego3g, I adjusted this, but the colors don’t match perfectly, because the VSCode themes are much more granular than the Prisma themes.

See the side-by-side comparison:

JavaScript
![js](https://user-images.githubusercontent.com/55815473/119070913-37bda680-b9bf-11eb-823d-3818f04ce6de.png)

HTML
![html](https://user-images.githubusercontent.com/55815473/119070909-37251000-b9bf-11eb-987f-b5fe6c7b9103.png)

CSS
![css](https://user-images.githubusercontent.com/55815473/119070908-35f3e300-b9bf-11eb-8252-6f957f261945.png)

**Comment by diego3g** [comment]
I invited you to be part of the Omni Organization so you we can create a new repository for the Prism theme :) 

Thanks <3

**Comment by martins-rafael** [comment]
I made the transfer the repository and opened a PR to add the theme to the main one :rocket:
