### ISSUE TITLE
Omni for MultiMC

### ISSUE THREAD

**Issue by wictornogueira** [getomni/omni#43]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [X] The theme follows the [template](https://github.com/getomni/template);
- [X] The theme follows the Omni Color Palette;
- [X] The branch name is `main` (we will keep this name pattern from now on);
- [X] The theme has correct instructions on how to install it;
- [X] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** MultiMC
**Application URL** https://multimc.org/
**GitHub URL:** https://github.com/wictornogueira/multimc

**Comment by jpedroschmitz** [comment]
Hey @wictornogueira. Thanks for creating the theme!

I have reviewed it, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization. After that, you can transfer your repository to the org.

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

**Comment by jpedroschmitz** [comment]
Hey, I saw that you transferred the repository!

Now you need to create a PR to add it to this main repository! If you need any help, let me know.

Don't forget to share the theme on forums, communities, and social media!

Thanks for creating it 💜
