### ISSUE TITLE
Omni for Termux

### ISSUE THREAD

**Issue by gsbenevides2** [getomni/omni#44]
## Omni for Termux

Termux is an Android application that emulates a Linux terminal.  With this it is possible to install several packages such as NodeJS, Python, Vim and others. I used the Omni color scheme in Hyper as a basis.

[Repo](https://github.com/gsbenevides2/termux)

![Screenshot_20210621-225129](https://user-images.githubusercontent.com/45762112/122852146-858f3c80-d2e6-11eb-95fa-51008a62452d.png)

**Comment by jpedroschmitz** [comment]
Hey @gsbenevides2, could you please follow the new theme template?

**Comment by gsbenevides2** [comment]
Hi @jpedroschmitz , I made the changes to the color scheme based on the VSCode repository with the Readme of this repository.  Also update the Screenshot.
 Thanks for answering.

**Comment by jpedroschmitz** [comment]
Thanks a lot @gsbenevides2, I really appreciate the changes!

I have reviewed it, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization.

Before transferring the repo, make sure to change all URLs to match the new repository link.

Also, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by jpedroschmitz** [comment]
Hey, I saw that you transferred the theme repo!

Don't forget to share the theme on forums, communities, and social media!

Thanks for creating it 💜
