### ISSUE TITLE
BetterDiscord

### ISSUE THREAD

**Issue by JonathanFerraz** [getomni/omni#47]
## Thanks for Omni theme!

BetterDiscord is an extension for Discord that allows you to install plugins and themes in discord, and you can have several customizations and adjustments that are not possible by the native application.

**Application:**  Discord (BetterDiscord)
**Application URL** https://betterdiscord.app/
**GitHub URL:** https://github.com/JonathanFerraz/better-discord

**Comment by diego3g** [comment]
Thanks for the contribution. I liked it a lot. I'll take some time to merge this one with the main Omni organization during the next days.

**Comment by jpedroschmitz** [comment]
The repository is no longer available. I am closing it.
