### ISSUE TITLE
Omni for XFCE Terminal

### ISSUE THREAD

**Issue by AllanCapistrano** [getomni/omni#48]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** XFCE Terminal
**Application URL:** https://docs.xfce.org/apps/terminal/start
**GitHub URL:** https://github.com/AllanCapistrano/xfce4-terminal

**Comment by jpedroschmitz** [comment]
Hey @AllanCapistrano, I have reviewed the theme, and we can include it in the organization. 🎉 

Before transferring the repo, make sure to change all URLs to match the new repository link.

Also, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by jpedroschmitz** [comment]
Thanks, @AllanCapistrano!
