### ISSUE TITLE
Omni for Better Discord

### ISSUE THREAD

**Issue by datsfilipe** [getomni/omni#49]
If you have already created a theme, make sure you check the following requirements:

- [x]  The theme follows the [template](https://github.com/getomni/template);
- [x]  The theme follows the Omni Color Palette;
- [x]  The branch name is `main` (we will keep this name pattern from now on);
- [x]  The theme has correct instructions on how to install it;
- [x]  The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Better Discord
**Application URL** https://betterdiscord.app/
**GitHub URL:** https://github.com/datsfilipe/better-discord

**Comment by jpedroschmitz** [comment]
@diego3g, any feedback here? Maybe worth changing that green for icons.

**Comment by datsfilipe** [comment]
hello, @jpedroschmitz, on version 2 I've changed the green color for icons, now it's purple.
