### ISSUE TITLE
Omni for Deepin Terminal

### ISSUE THREAD

**Issue by ermesonsampaio** [getomni/omni#50]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Deepin Terminal
**Application URL** https://www.deepin.org/en/original/deepin-terminal/
**GitHub URL:** https://github.com/ermesonsampaio/deepin-terminal

**Comment by jpedroschmitz** [comment]
Hey @AllanCapistrano, I have reviewed the theme, and you're using the wrong purple and comment.

- Replace all `189,147,249` with `152,139,199`
- Replace all `98,114,164` with `72,60,103`

After changing it, we're good to go! 🎉

**Comment by ermesonsampaio** [comment]
Hi @jpedroschmitz, I made the changes!

**Comment by jpedroschmitz** [comment]
Nice @joaom00! Thanks a lot =D

I'll be sending an invite for you to join the organization.

Before transferring the repo, make sure to change all URLs to match the new repository link.

Please, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻

**Comment by jpedroschmitz** [comment]
We really appreciate your help and effort in creating the theme! I have updated everything, and the theme is ready!

Don't forget to share it on social media (if you post something on Twitter, [mention me](https://twitter.com/jpedroschmitz), so I can retweet it) 💜 

Thanks again!
