### ISSUE TITLE
Omni for Neovim

### ISSUE THREAD

**Issue by joaom00** [getomni/omni#51]
## Add a new theme to the organization

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template);
- [x] The theme follows the Omni Color Palette;
- [x] The branch name is `main` (we will keep this name pattern from now on);
- [x] The theme has correct instructions on how to install it;
- [x] The repository name is lowercase and contains just the application name. E.g. `visual-studio-code`.

**Application:** Neovim
**Application URL** https://neovim.io/
**GitHub URL:** https://github.com/joaom00/neovim

**Comment by jpedroschmitz** [comment]
Hey @joaom00, I have reviewed the theme, and we can include it in the organization. 🎉 

I'll be sending an invite for you to join the organization.

Before transferring the repo, make sure to change all URLs to match the new repository link.

Please, open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 

---

Just one question: can we change the package name [here](https://github.com/joaom00/neovim/blob/main/INSTALL.md#-installation) to:

```
use 'getomni/neovim'
```

You can still publish it.

**Comment by jpedroschmitz** [comment]
Thanks, @joaom00!
