### ISSUE TITLE
Omni for Kitty

### ISSUE THREAD

**Issue by Mdsp9070** [getomni/omni#8]
## Add a new theme to the organization?

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template).
- [x] The theme follows the Omni Color Palette.
- [x] The branch name is `main` (we will keep this name pattern from now on)
- [x] The theme has instructions on how to install it.

**Application:** Kitty terminal emulator
**GitHub URL:** https://github.com/Mdsp9070/kitty

Well, long time ago I created a standalone version for Kitty, here's the old repo URL: https://github.com/Mdsp9070/kitty-omni

I'm glad that you'd decided to receive officials contributions!

**Comment by jpedroschmitz** [comment]
Hey @Mdsp9070, thanks for your contribution 💜 

Taking a look at the theme, the theme colors file is missing. Also, this issue is a duplicate of #6.

I think we can continue the conversation on the first issue and include you and @gabrielcaussi as contributors to the theme.

What do you think?

**Comment by Mdsp9070** [comment]
Indeed... I forgot to push the theme color file haha. I fixed it!

Yes! I agree with you! Just want to notice that @gabrielcaussi 's theme don;t contemplate inactive tabs and so on! But this can be easy solved!

**Comment by jpedroschmitz** [comment]
Nice, I think you can open a PR on the @gabrielcaussi theme, improving it.

Or you can wait till we merge the theme on the Omni org and then open a PR.

After that, we can include you as a team member =D

Thanks for your comprehension and help 💜

**Comment by Mdsp9070** [comment]
I'll open a PR on his repository! Thank you for the attencion!

**Comment by jpedroschmitz** [comment]
Hey @Mdsp9070, we have included the Kitty theme on the Omni org.

If you'd like to open a PR, we will be glad to receive it =D

I really appreciate any help you can provide.

**Comment by Mdsp9070** [comment]
OK! I'll open the PR!

Actually, I that am really glad to contribute (:

**Comment by gabrielcaussi** [comment]
@Mdsp9070, if you can change the screenshot when making the pull request. It got a bad quality because I use Window Manager and I had to take the printscreen off a virtual machine. Thanks!

**Comment by Mdsp9070** [comment]
No problem! I'll use mine!

**Comment by Mdsp9070** [comment]
Hey @gabrielcaussi I just openned the PR!
