### ISSUE TITLE
Omni for Alacritty

### ISSUE THREAD

**Issue by Mdsp9070** [getomni/omni#9]
## Add a new theme to the organization?

If you have already created a theme, make sure you check the following requirements:

- [x] The theme follows the [template](https://github.com/getomni/template).
- [x] The theme follows the Omni Color Palette.
- [x] The branch name is `main` (we will keep this name pattern from now on)
- [x] The theme has instructions on how to install it.

**Application:** Alacritty terminal emulator
**GitHub URL:** https://github.com/Mdsp9070/alacritty

Yeat another theme that I'd created as a standalone version haha, here's the old repo URL: https://github.com/Mdsp9070/alacritty-omni

**Comment by jpedroschmitz** [comment]
Hey @Mdsp9070. Thanks for creating the theme!

I have reviewed it, and we can include the theme in the organization. 🎉 

I'll be sending an invite for you to join the organization. After that, you can transfer your repository to the org.

Just make sure to open a PR and include the theme on the [main repository](https://github.com/getomni/omni) 👊🏻 
Also, after the transfer, make sure to change all URLs to match the new repository link.

**Comment by Mdsp9070** [comment]
Ok! Thank you! I already openned the PR and changed the url!

**Comment by jpedroschmitz** [comment]
That's perfect. Remember to accept the invitation to join the org and transfer the repository.

Let me know if you have any questions!

**Comment by Mdsp9070** [comment]
So, I successfully merged the PR. Thank you for the attention!
